### ISSUE TITLE
installed games and recently played not working

### ISSUE THREAD

**Issue by FregrinZ** [aanderse/plugin.program.steam.library#12]
Hello,

I just tried this addon again, not sure if still working on this but am getting error message when try installed games or recently played?

Have i done something wrong perhaps

**Comment by aanderse** [comment]
@FregrinZ could you please either paste the text of the error, or take a picture of the error and upload it if you don't mind?

**Comment by FregrinZ** [comment]
just says steam library error, check log for more details ?

08:31:42.526 T:6948   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.steam.library/installed
08:31:42.526 T:6948   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.steam.library/installed) failed

**Comment by aanderse** [comment]
Do you get the same error for recently played games?

I develop on Linux and don't have access to a Windows box. I was informed that the installed games functionality I wrote won't work on Windows because Steam does something entirely different on Windows than it does for Mac and Linux. I believe I know how to implement the code on Windows, but without a Windows dev box it seems a bit difficult to develop.

**Comment by aanderse** [comment]
If you turn on kodi debugging, try the recent games list entry again, then paste the relevant part of your kodi.log I'd have a better idea.

**Comment by aanderse** [comment]
Thanks for the log, exactly what I was looking for. Someone was kind enough to write the missing code for the installed games menu on Windows, so I'll try to put a new release out tomorrow. This should fix at least one of your errors.

**Comment by aanderse** [comment]
New version out: https://github.com/aanderse/plugin.program.steam.library/archive/0.6.1.zip

Please let me know if this fixes this installed games list. As far as recently played games, there is a known bug (I haven't got around to fixing yet...) in the recently played games list if you have no recently played games. See issue #9 for this.

The reason I haven't got around to fixing this yet is that my kid is keeping the recently played games list populated... so I haven't been able to test the fix.

Please re-open this issue if the installed games list is not working after updating.

**Comment by FregrinZ** [comment]
seems to be fixed now , thanks
