### ISSUE TITLE
Installed games folder is empty

### ISSUE THREAD

**Issue by Redneckita** [aanderse/plugin.program.steam.library#15]
Hi, first I would love to say thank you for making this possible. It's a total game changer!
The only issue I found is that the "installed games" folder in the add-on is empty even though I have some titles downloaded and ready to play.

I'm using Kodi 18 + Openbox on Ubuntu Bionic mini.iso. Everything is up to date, 'cause I installed this system a couple days ago...

Let me know if you need a log file or additional details! Would love to have it working ;)

Thanks in advance and keep up the good work!

**Comment by aanderse** [comment]
Yes a log file would be great please. The other menus have games showing up?

**Comment by Redneckita** [comment]
> Yes a log file would be great please. The other menus have games showing up?

Yes, the other folders are populated.

Here is the log (i've hidden some data, like steam ID and API or usernames for various services)
[kodi.log](https://github.com/aanderse/plugin.program.steam.library/files/4005912/kodi.log)


And this is registry.vdf
`"Registry"
{
	"HKLM"
	{
		"Software"
		{
			"Valve"
			{
				"Steam"
				{
					"SteamPID"		"1466"
					"TempAppCmdLine"		""
				}
			}
		}
	}
	"HKCU"
	{
		"Software"
		{
			"Valve"
			{
				"Steam"
				{
					"RunningAppID"		"0"
					"language"		"italian"
					"AutoLoginUser"		"/////////////"
					"RememberPassword"		"1"
					"SourceModInstallPath"		"/home/ggtop/.local/share/Steam/steamapps\sourcemods"
					"Rate"		"30000"
					"AlreadyRetriedOfflineMode"		"0"
					"Apps"
					{
						"261640"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
							"name"		"Borderlands: The Pre-Sequel"
						}
						"275690"
						{
							"Installed"		"1"
						}
						"289881"
						{
							"Installed"		"1"
						}
						"321430"
						{
							"Installed"		"1"
						}
						"316410"
						{
							"Installed"		"1"
						}
						"241100"
						{
							"Updating"		"0"
						}
						"236870"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"310560"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"201700"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"255220"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"345660"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"1113280"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"300380"
						{
							"Installed"		"1"
							"Updating"		"0"
							"Running"		"0"
						}
						"228980"
						{
							"Updating"		"0"
							"Installed"		"1"
							"Running"		"0"
						}
						"439870"
						{
							"Installed"		"1"
						}
						"439890"
						{
							"Installed"		"1"
						}
						"440930"
						{
							"Installed"		"1"
						}
						"440940"
						{
							"Installed"		"1"
						}
						"440960"
						{
							"Installed"		"1"
						}
						"440961"
						{
							"Installed"		"1"
						}
						"440962"
						{
							"Installed"		"1"
						}
						"282091"
						{
							"Installed"		"1"
						}
						"282092"
						{
							"Installed"		"1"
						}
						"289020"
						{
							"Installed"		"1"
						}
						"289021"
						{
							"Installed"		"1"
						}
						"289022"
						{
							"Installed"		"1"
						}
						"289023"
						{
							"Installed"		"1"
						}
						"289024"
						{
							"Installed"		"1"
						}
						"289025"
						{
							"Installed"		"1"
						}
						"324130"
						{
							"Installed"		"1"
						}
						"347450"
						{
							"Installed"		"1"
						}
						"345900"
						{
							"Installed"		"1"
						}
						"392880"
						{
						"Installed"		"1"
						}
						"392900"
						{
							"Installed"		"1"
						}
					}
					"StartupMode"		"0"
				}
			}
		}
	}
}
`

The games i have installed are Borderlands Pre Sequel, Dirt Rally, Dirt Showdown, Grid Autosport, Hitman, Ride and Road Redemption.

Thanks for the quick reply!

**Comment by Redneckita** [comment]
It works, thanks man! If you would like to add localizations feel free to ask.
I can help with Italian at the very least, or others with some effort!
Wish you a good day
