### ISSUE TITLE
Move content of addon.py

### ISSUE THREAD

**Issue by Razzeee** [aanderse/plugin.program.steam.library#2]
Hey there,

if you like to improve your startup time, best practice is to have just some basics in addon.py and move everything else to a different .py file. As kodi caches all files but the `addon.py` in your case.

**Comment by aanderse** [comment]
I've tried moving the code into the resources/ folder in a file called main.py and then calling the function from addon.py but I keep getting an Import Error which says there is 'No module named resources'.

I'm relatively new to python but this seemed pretty straight forward... Do I need to add resources to a system path so python knows how to access the main.py file under this folder?

Thank you.

**Comment by Razzeee** [comment]
Create an empty `__init__,py` file see https://github.com/trakt/script.trakt/blob/master/resources/__init__.py

**Comment by aanderse** [comment]
Thanks again Razzee!
