### ISSUE TITLE
installed games

### ISSUE THREAD

**Issue by FregrinZ** [aanderse/plugin.program.steam.library#3]
sorry if this is wrong place put this was looking somewhere contact you.

Would it be possible to add a category or section for games i have installed in steam and non steam games ? or is that to complex?

I love we have so far with recent and all games.

**Comment by aanderse** [comment]
This is the perfect place to report this. Thank you for the suggestion. I like the idea of an installed games section. I'll look into this and report back.

**Comment by FregrinZ** [comment]
That would be great, when do you think this will get released?

**Comment by aanderse** [comment]
I'd love to tell you a date but I really can't commit to anything at this point. I did actually start the code, so hopefully I'll get back to it in the next month?

**Comment by aanderse** [comment]
@FregrinZ I'm sorry I never got back to this until now. Please let me know if you have any issues.
