### ISSUE TITLE
Steam as widget

### ISSUE THREAD

**Issue by FregrinZ** [aanderse/plugin.program.steam.library#4]
When I go into your addon works great games are A to Z. But if I set it up as widget seems all games is quite random ? I tried couple of skins but same thing ? Is this a bug or me?
[https://ibb.co/cBw2m7](url)

**Comment by aanderse** [comment]
Is this just for recently played games, or all games?

**Comment by FregrinZ** [comment]
its all games it seems start at half life and always is the same

![img_0040](https://user-images.githubusercontent.com/16095651/39955721-13e609e6-55cc-11e8-9799-76154c0c984e.jpg)
![img_0041](https://user-images.githubusercontent.com/16095651/39955722-14068f86-55cc-11e8-9c39-18e66a58e37d.jpg)

**Comment by FregrinZ** [comment]
Ok I hope you can find a fix, really like having widgets displaying my games.

**Comment by FregrinZ** [comment]
![image](https://user-images.githubusercontent.com/16095651/39965102-e48ad680-568a-11e8-91eb-346467a35c6f.jpg)

Fixed it I had to change A to Z in widgets from none/ default to label in the skin.grrr

**Comment by aanderse** [comment]
glad to hear the issue is resolved!
